service: 'SwipeMeIn'

resources:


provider:
  name: 'aws'
  runtime: 'nodejs8.10'
  stage: 'dev'
  region: 'us-east-1'
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:us-east-1:*:*"


functions:
  test:
    handler: handler.hello
    events:
      - http:
          method: POST
          path: /messages
          private: false
  testarik:
    handler: arik_handler.thisIsATest
    events:
      - http:
          method: GET
          path: /messages
          private: false
  dbTest:
    handler: arik_handler.dbTestCreate
    events:
      - http:
          method: POST
          path: /dbTest
          private: false
  postSwipe:
    handler: arik_handler.postSwipe
    events:
      - http:
          method: POST
          path: /postSwipe
          private: false
  postDonation:
    handler: arik_handler.postDonation
    events:
      - http:
          method: POST
          path: /postDonation
          private: false
  getDonation:
    handler: arik_handler.getDonation
    events:
      - http:
          method: GET
          path: /getDonation
          private: false
